apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: pullzones.bunny-cdn-operator.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: bunny-cdn-operator.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                originUrl:
                  type: string
                storageZoneId:
                  type: integer
                storageZoneRef:
                  type: object
                  properties:
                    name:
                      type: string
                    namespace:
                      type: string
                  required:
                    - "name"
                    - "namespace"
                zoneType:
                  type: string
                  pattern: "^(premium|volume)"
                  default: "volume"
                zoneSecurityEnabled:
                  type: boolean
                  default: true
                errorPageWhiteLabel:
                  type: boolean
                  default: true
                enabledCacheSlice:
                  type: boolean
                  default: true
                monthlyBandwidthLimit:
                  type: integer
                  minimum: 0
                  default: 0
                deletionPolicy:
                  type: string
                  pattern: "^(delete|retain)"
                  default: "retain"
            status:
              type: object
              properties:
                ready:
                  type: boolean
                message:
                  type: string
                observedGeneration:
                  type: integer
                  format: int64
                id:
                  type: integer
      subresources:
        # status enables the status subresource.
        status: {}
      additionalPrinterColumns:
        - name: Ready
          type: boolean
          jsonPath: .status.ready          
        - name: Message
          type: string
          jsonPath: .status.message
        - name: PullZoneID
          type: number
          jsonPath: .status.id

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: pullzones
    # singular name to be used as an alias on the CLI and for display
    singular: pullzone
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: PullZone
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - "plz"
